### ISSUE TITLE
Entity not numeric

### ISSUE THREAD

**Issue by BebeMischa** [tomaae/homeassistant-openmediavault#71]
After today's update, 4 of the 5 disks do not report temperature anymore. Worked fine with 1.1.7.

Any idea, what changed here?

Ask any info you need, dear Tomaae ;-)

![image](https://user-images.githubusercontent.com/73079275/157536233-ca565831-89ca-47cd-9173-31a100c75b8e.png)

The sensors are present and working, they just do no display...

![image](https://user-images.githubusercontent.com/73079275/157536687-56d411d1-4ed7-4602-82ea-e5b991e00bf5.png)

example of card code:

```
type: gauge
min: 0
max: 100
entity: sensor.omv_sda
severity:
  green: 0
  yellow: 65
  red: 70

```

Thanks in advance ;-)
